### ISSUE TITLE
subTitle vs menuTitle

### ISSUE THREAD

**Issue by styks1987** [greglobinski/gatsby-starter-personal-blog#13]
I am getting an issue after editing some of the files and recompiling.

It seems changing `menuTitle` to `subTitle` in your layouts/index.js file fixes the pages query

Any idea why?

**Comment by greglobinski** [comment]
@styks1987 I'm a little confused do you really wanted to say "fixes" not "breaks"?
Secondly, I need more details to say anything.

**Comment by styks1987** [comment]
@greglobinski 
My apologies. I found my issue. I deleted the starters page and so that removed the menuTitle which broke the queries.
