### ISSUE TITLE
navigate has some problems

### ISSUE THREAD

**Issue by quangson91** [greglobinski/gatsby-starter-personal-blog#2]
I think we have some problems when navigate.
Example:
1. From home screen.
2. Click search many times.
3. Click back button.
Expect:
Go to home screen. 
Actual: Still keep on search screen (when the number of press back == the number of press search => go home).

I think we can make it better.
Eg: we can check if a current is `search` screen -> user clicks search -> we do not put it on the stack.

**Comment by greglobinski** [comment]
Hi @quangson91 , nice finding, but not only the search button behaves like that, all links on the page behave this way :)

Seems that the behavior is build in into `gatsby-link` https://www.gatsbyjs.org/packages/gatsby-link/ . Links on the Gatsby docs sidebar https://www.gatsbyjs.org/docs/gatsby-lifecycle-apis/ behave the same way.

If you confirm, could you please open an issue for Gatsby https://github.com/gatsbyjs/gatsby

**Comment by quangson91** [comment]
Yes, Thank you for explaining.
I will do that!
I will close this issue.

----

Thank you for build this starter.
I love this & would to use this starter for my blog :)

Could you create some docs for this starters?
(Eg, disable animation when translation page).

Thank you!

**Comment by greglobinski** [comment]
Thaks,
Sure, I'm working on it. I think, this week I will launch a small site about my starters with instructions.

**Comment by quangson91** [comment]
Thank you so much :)
