### ISSUE TITLE
GraphQL Error after fresh clone

### ISSUE THREAD

**Issue by joshuamabina** [greglobinski/gatsby-starter-personal-blog#20]
> **Disclaimer** I've just started playing around with gatsby. I think your starters are friggin' awesome.

I keep hitting this error after a fresh clone.

> **GraphQL Error** There was an error while compiling your site's GraphQL queries.
  GraphQLParser

I thought it was a result of not specify `FB_APP_ID`, but, even when I did, it persisted.

Any assistance will be highly appreciated.

**Comment by greglobinski** [comment]
@joshuamabina 
The error is with `gatsby develop` or `gatsby build`?

**Comment by joshuamabina** [comment]
@greglobinski The error is with `gatsby develop`.

I hadn't read the **install-personal-blog-starter** post. Thank you, it was insightful.

I was led to assume the starter would work only with features whose **variables** have been specified, when I saw this:

      indexName: process.env.ALGOLIA_INDEX_NAME ? process.env.ALGOLIA_INDEX_NAME : ""

Maybe that is not the case?

**Comment by greglobinski** [comment]
@joshuamabina, 
you have to have the `.env` file with described variables, the `gatsby develop` should work with undefined values for the variables, but they have to be declared. For `gatsby build` you have to define working values for the ENV variables in other case the command will through an error because of Algolia. But as I described you can turn of the plugin temporarily.

**Comment by greglobinski** [comment]
This setup
```    
algolia: {
      appId: process.env.ALGOLIA_APP_ID ? process.env.ALGOLIA_APP_ID : "",
      searchOnlyApiKey: process.env.ALGOLIA_SEARCH_ONLY_API_KEY
        ? process.env.ALGOLIA_SEARCH_ONLY_API_KEY   : "",
      indexName: process.env.ALGOLIA_INDEX_NAME ? process.env.ALGOLIA_INDEX_NAME : ""
    },
    facebook: {
      appId: process.env.FB_APP_ID ? process.env.FB_APP_ID : ""
    }
```
should let you run `gatsby develop` without throwing Error when there is no `.env` file. 

Could you please paste here the whole error message you get.

**Comment by mpolinowski** [comment]
Just a confirmation - I used develop without adding a Algolia/FB ID - only added the .env file:

```
GOOGLE_ANALYTICS_ID=...
ALGOLIA_APP_ID=...
ALGOLIA_SEARCH_ONLY_API_KEY=...
ALGOLIA_ADMIN_API_KEY=...
ALGOLIA_INDEX_NAME=...
FB_APP_ID=...
```

This only breaks the build command.


Btw. @greglobinski thank you for this amazing starter!
