### ISSUE TITLE
How do I replace the avatar?

### ISSUE THREAD

**Issue by BobWalsh** [greglobinski/gatsby-starter-personal-blog#22]
Excellent Gatsby Example @greglobinski, but how do I change your avatar?

**Comment by greglobinski** [comment]
Thank you @BobWalsh ,

avatar is an image imported into two components `src/components/InfoBox/InfoHeader.js` and `src/components/Post/PostAuthor.js`

```
import avatar from "../../images/jpg/avatar.jpg";
```
you can change the import statements or replace the `src/images/jpg/avatar.jpg` file.
