### ISSUE TITLE
How to configure contact form?

### ISSUE THREAD

**Issue by DarrenCook** [greglobinski/gatsby-starter-personal-blog#24]
1. It might be nice if the mailto address came from content/meta/config.js.

2. Where does the form submit to, by default? Watching the network tab, I think the answer might be nowhere? In which case my question is what do I need to get it setup? (Ideally I want any submissions to arrive at the same email address; I don't mind setting up something server-side,  but I'm wondering if Gatsby already has some functionality for this?)

**Comment by greglobinski** [comment]
@DarrenCook 
I wrote in the README, 
"The contact form does not need any settings it should work out of the box if you deploy the website to Netlify", 
the key word in the sentence is "Netlify".

All the form's setup 
```
<ValidatorForm
        onSubmit={this.handleSubmit}
        onError={errors => console.log(errors)}
        name="contact"
        ref={f => (this.form = f)}
        data-netlify="true"
        data-netlify-honeypot="bot-field"
      >
```
are these two rows
```
        data-netlify="true"
        data-netlify-honeypot="bot-field"
```
they turn on the Netlify's form handling feature.
https://www.netlify.com/docs/form-handling/
