### ISSUE TITLE
hapijs / hoek security vulerability

### ISSUE THREAD

**Issue by doakheggeness** [greglobinski/gatsby-starter-personal-blog#25]
U
FTI. upon a git commit I got a 'vulnerablity' notice.
![vulnerability](https://user-images.githubusercontent.com/1179369/39451171-98eced1a-4c82-11e8-9ac4-6d871ea20cf7.JPG)

**Comment by greglobinski** [comment]
@doakheggeness 
Yeah, I know that and I'm observint the hoek https://github.com/hapijs/hoek/issues/247

**Comment by greglobinski** [comment]
@doakheggeness  What do you mean by "FTI."?

**Comment by doakheggeness** [comment]
FYI....for your information,   my bad
