### ISSUE TITLE
gatsby install

### ISSUE THREAD

**Issue by doakheggeness** [greglobinski/gatsby-starter-personal-blog#26]
Greg,
How odd, I have the same problem on my laptop. It compiles in the terminal, but localhost:8000 is blank on  all browsers. Windows 10 Pro X1 Carbon. I installed using 'gastby new.' My desktop works fine.

**Comment by greglobinski** [comment]
@doakheggeness What does it mean "the same problem"?

**Comment by doakheggeness** [comment]
I had the same issue when installing this on my Desktop computer. I had ytied installing using 'git clone' and npm and got a blank localhost:8000. You suggested trying installing using the 'gastby new' method which worked.

**Comment by greglobinski** [comment]
@doakheggeness , the same exact error in the console?

**Comment by doakheggeness** [comment]
Yes, the same error

**Comment by greglobinski** [comment]
Discussion moved to https://github.com/greglobinski/gatsby-starter-personal-blog/issues/27
