### ISSUE TITLE
_reactLifecyclesCompat.polyfill is not a function

### ISSUE THREAD

**Issue by DarrenCook** [greglobinski/gatsby-starter-personal-blog#27]
I did a `yarn upgrade`, and now though `gatsby develop` gives no errors, I get a blank page, and in the browser console I get:

    "_reactLifecyclesCompat.polyfill is not a function"
    TypeError: _reactLifecyclesCompat.polyfill is not a function
    Stack trace:
    ./node_modules/react-form-validator-core/lib/ValidatorComponent.js@http://localhost:8000/commons.js:78564:3
    __webpack_require__@http://localhost:8000/commons.js:585:12
    fn@http://localhost:8000/commons.js:109:20
    ./node_modules/react-form-validator-core/lib/index.js@http://localhost:8000/commons.js:78786:28
    __webpack_require__@http://localhost:8000/commons.js:585:12
    fn@http://localhost:8000/commons.js:109:20
   ...

It seems to be coming from the Contact form.

`gatsby build` fails with a very similar message:

    WebpackError: (0 , _reactLifecyclesCompat.polyfill) is not a function
     - ValidatorComponent.js:177 Object.componentWillMount.__suppressDeprecationWarning
    ~/react-form-validator-core/lib/ValidatorComponent.js:177:1
     - index.js:3 Object.defineProperty.value
    ~/react-form-validator-core/lib/index.js:3:1
     - index.js:3 Object.<anonymous>
    ~/react-material-ui-form-validator/lib/index.js:3:1
     - ContactForm.js:6 Object.defineProperty.value
    src/components/ContactForm/ContactForm.js:6:1

I ended up here because I tried deploying to netlify, and they gave the same error, even though `gatsby build` had worked for me just before I pushed to github!

**Comment by greglobinski** [comment]
@DarrenCook 
seams that the new version of `react-material-ui-form-validator` could be a source of that, my `yarn outdated` says that there was a 'Major Update backward-incompatible update'. So the `ContactForm.js` component probably needs to be updated in some way.

**Comment by DarrenCook** [comment]
Thanks for the hint

`yarn upgrade react-material-ui-form-validator@2.0.0-beta.4` fixed it. It seems the damage was done somewhere between beta.4 and beta.9.

(I got it working that way before I saw your react-lifecycles-compat suggestion, so cannot say if that approach would also work.)

**Comment by doakheggeness** [comment]
Installing 'react-lifecycles-compat' allowed localhost:8000 to load on my laptop in lieu of a blank page. Thanks
