### ISSUE TITLE
Removing a searching functionality and Algolia free plan usage

### ISSUE THREAD

**Issue by DarrenCook** [greglobinski/gatsby-starter-personal-blog#28]
I did the algolia sign-up. It is a 14-day free trial, and you cannot create an app on that trial. That maybe ought to be clearer, or have it disabled by default?

I didn't particularly need that search functionality, so commented out the gatsby-config.js entry. But I then went further and removed all references. For anyone else who wants to do this, that involved:

* the other algolia:{} entry in gatsby-config.js
* the plugin removed from package.json
* the references in src/components/InfoBox/StackIcons.js
* the references in src/components/Page/PageHeader.js

Then these files were removed completely:

* src/components/Search/Hit.js
* src/components/Search/Search.js
* src/components/Search/index.js
* src/pages/search.js

Finally, src/components/ActionsBar/ActionsBar.js needs editing to remove `searchOnClick` and the `<IconButton>` block that contains `<SearchIcon>`.

**Comment by greglobinski** [comment]
@DarrenCook  There is a free "Forever" comumnity plan https://www.algolia.com/pricing

![www algolia com_pricing laptop with mdpi screen](https://user-images.githubusercontent.com/32480082/39542242-519ccabc-4e48-11e8-87eb-589cab89891f.png)

**Comment by mpolinowski** [comment]
The Problem with the free plan is, that the allowed size of your markdown files is fairly limited - most of my blog entries failed because of that.

I am using your starter now without Algolia (as well as without Facebook) - for those who are interested in the modified fork:

https://github.com/mpolinowski/gatsby-starter-personal-blog

**Comment by greglobinski** [comment]
@mpolinowski 
There is not any problem with Algolia free plan. Sure, there is a chunk size limit 10kB but hey for lower paid plans the limit is 20kB. 

Your *.md files (https://github.com/mpolinowski/mpolinowski.github.io/blob/master/elasticsearch-kibana/index.html) weigh 50-80kB. And that means you would have to pay for, at least, Bussines plan to send your whole *.md files to Algolia index (the starter scripts works in this way).

It's not fault of Algolia that your *.md files are not actually *.md files :). I.m guessing, that you has moved your content from previous stack and that was the fasted way to relaunch the blog. But  for sure it's a bad practice to sending HTML to Alglia index, so it's good you don't ;)

And now, not in the case of your posts, but in general. 

Of course there are 'true' *.md files which could weigh more than 10-20kB, But it doesn't mean you have to immediately pay for the Businnes plan. You can split your content to smaller chunks. Instead sending 100 chunks which weighs 50kB each, you can send 1000 chunks which weighs 5kB each. The free plan has a 10K records limit. 

Of course that means you have to refactor the stater's code.  But it absolutely does not mean that something is wrong with Algolia free paln :)

https://www.algolia.com/doc/faq/basics/is-there-a-size-limit-for-my-index-records/
