### ISSUE TITLE
[Request feature] auto hide topbar & bottom bar while use reading

### ISSUE THREAD

**Issue by quangson91** [greglobinski/gatsby-starter-personal-blog#3]
I think on mobile devices, we can make new feature `auto hide topbar/bottom bar` while user reading.
![request_auto_hide](https://user-images.githubusercontent.com/6185205/37501410-e140a48a-2900-11e8-9a38-3aeee6dffe70.png)

**Comment by greglobinski** [comment]
Nice idea @quangson91. Would you be able to submit a PR with the new feature?

**Comment by quangson91** [comment]
@greglobinski I'm not good at js/css much.
But here is the implement.
http://embed.plnkr.co/mbMGaDhiudP6BIjQKwwy/preview
(I will try on my hand & create new PR if it works).

**Comment by quangson91** [comment]
on angular material, it seems we can simply be added:
`<md-toolbar md-scroll-shrink>` is the magic.

**Comment by quangson91** [comment]
Actually, I think  we can do something like this: http://jsfiddle.net/mariusc23/s6mLJ/31/

I also tried to add bellow code in `InfoBar` component.
```javascript
  handleScroll(event) {
    console.log("event: " + event);
  }

  componentDidMount() {
    window.addEventListener("scroll", this.handleScroll);
  }

  componentWillUnmount() {
    window.removeEventListener("scroll", this.handleScroll);
  }
```
`componentDidMount` called. But the method `this.handleScroll` never call :|
so I can't complete.
Do you have any suggestion?

**Comment by greglobinski** [comment]
That's fine @quangson91 , I asked you about PR because you wrote "we can make new feature".
I've added the feature to the to-do list.

About the code. It doesn't work because when you scrolling you do not scroll the content of the window but the content of the `Scrollbars` component.
