### ISSUE TITLE
Bug in react-form-validator-core inside ValidatorComponent.js

### ISSUE THREAD

**Issue by chaitanyagiri** [greglobinski/gatsby-starter-personal-blog#30]
Inside ValidatorComponent.js we are using `_reactLifecyclesCompat.polyfill()`  but in the module 'react-lifecycle-compat' the exported object does not have a polyfill() function instead it is directly been used.

I fixed it by removing the .polyfill() from _reactLifecyclesCompat.polyfill() and it worked for me.
It is a problem with react-form-validator-core probably some older version being used here.

**Comment by greglobinski** [comment]
@chaitanyagiri 
There is nothing like `_reactLifecyclesCompat.polyfill()` in the `ValidatorComponent.js` file the starter uses.
https://github.com/NewOldMax/react-form-validator-core/blob/0.4.1/src/ValidatorComponent.jsx
What's the problem?

**Comment by chaitanyagiri** [comment]
Please have a look at the selected line and the comment beneath it in the screenshot. In the comments the previous state is been explained and in the selected line I have shown how I corrected it.

![gatsby-bug01](https://user-images.githubusercontent.com/26071627/39717612-73593fd4-5251-11e8-8569-2e4a30931d27.png)

![gatsbybug04](https://user-images.githubusercontent.com/26071627/39717639-8548cdd6-5251-11e8-8f2c-d14e0d1901ba.png)

![polyfill 05](https://user-images.githubusercontent.com/26071627/39717652-8da8490c-5251-11e8-89ce-05c18521904a.png)

**Comment by greglobinski** [comment]
@chaitanyagiri 
first, 
you are talking about updated version of `react-form-validator-core`, the version of the package the starter uses (v 0.4.1) do not import `react-lifecycles-compat`, I gave you the link to the version the starter uses in the previous post, but once again:

v. 0.4.1 - starter uses this version
https://github.com/NewOldMax/react-form-validator-core/blob/0.4.1/src/ValidatorComponent.jsx
v. 0.4.4 - the latest one, the one about which you are probably talking about
https://github.com/NewOldMax/react-form-validator-core/blob/master/src/ValidatorComponent.jsx

as you can see the `import { polyfill } from 'react-lifecycles-compat';` is only in the second one

second. 
so you updated the package and have found the bug in the `react-form-validator-core` so please go to the package's github repo and create issue there. Sorry I have no time to take care of it now.

third
Thank you for the notice. It could be valuable when I or any other user  of the starter like you would like to upgrade the package.

Is there anything else you expect from me?

**Comment by chaitanyagiri** [comment]
Thankyou for this exhaustive comment it clearedmost of my doubts, as of now I do not have anything else to ask.
