### ISSUE TITLE
a tiny bug for Facebook comments colorScheme

### ISSUE THREAD

**Issue by khairendra** [greglobinski/gatsby-starter-personal-blog#31]
I have found a tiny bug in <code>/src/components/Post/PostComments.js</code>

```javascript
  return (
    <div id="post-comments" className={classes.postComments}>
      <FacebookProvider appId={facebook}>
        <Comments
          href={`${config.siteUrl}${slug}`}
          width="100%"
          colorscheme={props.theme.main.colors.fbCommentsColorscheme}  // Notice the S on "colorscheme", it should be "colorScheme" the parameter is case sensitive
        />
      </FacebookProvider>
    </div>
);
```
You can see my fix suggestion in the snippets above (in comment)

Thanks.

**Comment by greglobinski** [comment]
Thank you @khairendra 
Personally, I would not call that a bug. It does not produce any error, the theme property's name is exactly like that ( with the 'bug' ;)
```
 main: {
    colors: {
      background: colors.background,
      title: colors.gray,
      subTitle: colors.gray,
      meta: colors.gray,
      content: colors.dark,
      footer: colors.gray,
      contentHeading: colors.gray,
      blockquoteFrame: colors.lightGray,
      link: colors.accent,
      linkHover: colors.dark,
      fbCommentsColorscheme: "light" // #HERE#
    },
    sizes: {
      articleMaxWidth: "50em"
    },
```
But sure it's a deviation from a rule, and the property's name sholud be `fbCommentsColorScheme`. But we have to edit two files the component and the theme. Would you like to make a PR?

**Comment by khairendra** [comment]
Well, the reason i call it a very small bug is because if you use colorscheme not colorScheme, it will not match with property name inside react-facebook, so the property will not applied.

I find out about this because i use dark background on my theme color and set fbCommentsColorscheme: "dark" but does not work (fb comments still use light colorScheme) but when i change colorscheme to colorScheme in <code>/src/components/Post/PostComments.js</code> then it works (fb comments now use dark colorScheme) at least in my dev environment

And i think is fine just to change colorScheme in <code>/src/components/Post/PostComments.js</code>, we don't need to change the theme property's name.

Sure i will create pull request. Just give me a moment.

**Comment by greglobinski** [comment]
@khairendra 
Sure you are absolutely right, I did not get what you are pointing at. I focused on `fbCommentsColorscheme` but you were talking about the `colorscheme` prop of the `Comment` component. 

You're right again, the change in `/src/components/Post/PostComments.js` will be enough.

Thank you

**Comment by greglobinski** [comment]
And it was a but absolutely :)

**Comment by khairendra** [comment]
thanks. I will close this now
