### ISSUE TITLE
Sharp lib require x64 arch

### ISSUE THREAD

**Issue by Huaoe** [greglobinski/gatsby-starter-personal-blog#46]
> yarn develop
Error: Cannot find module '../build/Release/sharp.node'

see Sharp doc : http://sharp.pixelplumbing.com/en/stable/install/
Only 64-bit (x64) node.exe is supported.

**Comment by greglobinski** [comment]
Sorry @Huaoe but I do not understand, could you please explicate your issue?

**Comment by Huaoe** [comment]
It's just a WARNING for others who would try.
I'm on a windows 32 bits and I can't install Sharp lib.
I'll probably migrate to Ubuntu soon ;)

**Comment by greglobinski** [comment]
Thank you.
