### ISSUE TITLE
Page slug is prefixed in wide view but not in mobile view

### ISSUE THREAD

**Issue by manrajgrover** [greglobinski/gatsby-starter-personal-blog#51]
If you see [blog](https://manrajsingh.in/blog), you will notice page slug is prefixed (with `/blog`) in `InfoMenu` but not in `TopMenu`. I'm currently debugging this and not sure from where it is originating.

Source Code is [here](https://github.com/manrajgrover/blog)

**Comment by manrajgrover** [comment]
This happens because TopMenu component does not make use of `Link` component from `gatsby-link`. I've fixed this. Would you like a PR for it?

**Comment by greglobinski** [comment]
@manrajgrover 
Sure, send a PR
