### ISSUE TITLE
Error: Cannot find module '../build/Release/sharp.node'

### ISSUE THREAD

**Issue by hiteshsahu** [greglobinski/gatsby-starter-personal-blog#59]
I tried deploying site on Netlify but it is showing error

```
12:46:53 PM: success open and validate gatsby-config — 0.010 s
12:46:53 PM: success copy gatsby files — 0.020 s
12:46:54 PM: error UNHANDLED EXCEPTION
12:46:54 PM: 
12:46:54 PM:   Error: Cannot find module '../build/Release/sharp.node'
12:46:54 PM:   
12:46:54 PM:   - v8-compile-cache.js:159 require
12:46:54 PM:     [repo]/[v8-compile-cache]/v8-compile-cache.js:159:20
12:46:54 PM:   
12:46:54 PM:   - constructor.js:10 Object.<anonymous>
12:46:54 PM:     [repo]/[gatsby-plugin-sharp]/[sharp]/lib/constructor.js:10:15
```

**Comment by Jamiebullock87** [comment]
I get this too
success open and validate gatsby-config — 0.010 s
success copy gatsby files — 0.018 s
error UNHANDLED EXCEPTION


  Error: Cannot find module 'sharp'
  
  - v8-compile-cache.js:159 require
    [blog-template]/[v8-compile-cache]/v8-compile-cache.js:159:20
  
  - extend-node-type.js:33 Object.<anonymous>
    [blog-template]/[gatsby-transformer-sharp]/extend-node-type.js:33:13
  
  - v8-compile-cache.js:178 Module._compile
    [blog-template]/[v8-compile-cache]/v8-compile-cache.js:178:30
  
  - v8-compile-cache.js:159 require
    [blog-template]/[v8-compile-cache]/v8-compile-cache.js:159:20
  
  - gatsby-node.js:16 Object.<anonymous>
    [blog-template]/[gatsby-transformer-sharp]/gatsby-node.js:16:38
  
  - v8-compile-cache.js:178 Module._compile
    [blog-template]/[v8-compile-cache]/v8-compile-cache.js:178:30
  
  - module.js:11 require
    internal/module.js:11:18
  
  - api-runner-node.js:87 runAPI
    [blog-template]/[gatsby]/dist/utils/api-runner-node.js:87:20
  
  - api-runner-node.js:187 
    [blog-template]/[gatsby]/dist/utils/api-runner-node.js:187:33

after installing the starter theme
