### ISSUE TITLE
Removing the link from images within markdown posts

### ISSUE THREAD

**Issue by Jamiebullock87** [greglobinski/gatsby-starter-personal-blog#60]
Is there any way I can remove the links from images placed within the markdown files?

I have tried setting the link manually to `#` for example `![image-alt-txt](./imagepath.png)(#)` but this doesnt work.

All images are wrapped within an anchor element no matter what. Is this perhaps an issue with gatsby image instead and how its processed? I don't necessarily want all images to link to the actual image.

**Comment by greglobinski** [comment]
@Jamiebullock87 Sure, set the `linkImagesToOriginal` of the [gatsby-remark-images](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-remark-images) plugin to `false`
