### ISSUE TITLE
Shouldn't `react` be in package.json?

### ISSUE THREAD

**Issue by leoj3n** [greglobinski/gatsby-starter-personal-blog#61]
Just curious if there's a reason the `package.json` omits `react` as an explicit dependency?

**Comment by leoj3n** [comment]
I guess things like `react` and `webpack` come inherently from `gatsby`?

**Comment by greglobinski** [comment]
@leoj3n , this is starter for Gatsby v1, the React is a dependency of gatsby itself, in this particular it's dependency of `gatsby-plugin-react-next`, for use of React 16. Gatsby v2 works as you expect, React is explicity listed in package.json
