### ISSUE TITLE
Is this double export valid JS?

### ISSUE THREAD

**Issue by leoj3n** [greglobinski/gatsby-starter-personal-blog#62]
https://github.com/greglobinski/gatsby-starter-personal-blog/blob/c679c38c97679c621412f801400daa3dbf439108/gatsby-ssr.js#L41-L45

Seems like the second `exports.onRenderBody` would override the first one.

**Comment by greglobinski** [comment]
@leoj3n, sure the second declaration, but the first one is 'empty', the `setHeadComponent([])` return nothing so for the starter it doesn't matter it exist or not, but yes it should be removed. Thank you for pointing out.
