### ISSUE TITLE
Why two lockfiles?

### ISSUE THREAD

**Issue by leoj3n** [greglobinski/gatsby-starter-personal-blog#63]
Any reason to include [`yarn.lock`](https://github.com/greglobinski/gatsby-starter-personal-blog/blob/master/yarn.lock) in addition to [`package-lock.json`](https://github.com/greglobinski/gatsby-starter-personal-blog/blob/master/package-lock.json)?

**Comment by greglobinski** [comment]
@leoj3n That's good question, till now I did not care about it. I use Yarn, so I have to ignore `packgage-lock.json`. Honestly, I even don't know from where and when it's generated. I will investigate it. Thank you for pointing it out.
