### ISSUE TITLE
cannot get webp assets to work :(

### ISSUE THREAD

**Issue by escapiststupor** [greglobinski/gatsby-starter-personal-blog#67]
Hi Greg,

Thanks for your wonderful starter. For some reason I can't get webp static assets working when deploying to my gh-pages. Not sure if it's a problem with `gatsby-source-filesystem`; it looks like these webps contain only `siteUrl` and are missing the `pathPrefix`. If I manually add `pathPrefix` and try to `GET` that resource it is indeed on the server.
The rest of the images worked just fine. Not sure what is going on here :( 
Thank you in advance.

**Comment by greglobinski** [comment]
@escapiststupor 

Before you call `gh-pages` try first clear cache and public folders
```
 rm -rf .cache\ public\
```
After that call `gatsby build` and only then deploy to gh-pages.

**Comment by greglobinski** [comment]
@escapiststupor 

Or add `deploy` script to your package.json
```
"scripts": {
      "deploy": "rimraf .cache public/ && gatsby build --prefix-paths && gh-pages -d public"
      ...
```
and use 
```
yarn deploy
```
to clear + build + deploy at once.

**Comment by escapiststupor** [comment]
Thank you Greg for your help and your wonderful starter. It worked like a charm! I didn't know gatsby keeps a cache ˊˋ
