### ISSUE TITLE
Bug in Url History & current URL

### ISSUE THREAD

**Issue by mansona** [greglobinski/gatsby-starter-personal-blog#69]
Hi there 👋 

I was just shown the demo for this project (looks really slick btw 😍) but I noticed a little issue that you might be interested in hearing about.

### Steps to reproduce: 
- Go to this site https://gatsby-starter-personal-blog.greglobinski.com/ 
- Click the `about` link which brings you to https://gatsby-starter-personal-blog.greglobinski.com/about/
- Click the avatar in the top left which brings you back to home
- Click on any of the blogs in the main list
- Hit **back** in the browser

### Expected behaviour
I would have expected to have gone back to the homepage (or the index page) with the list of all the blogs.

### Actual behaviour
I go back to the `about` page

### Observations
I notice that the url doesn't change when you click the avatar in the topo left which should bring you back home 🤔 I assume that the routing system isn't dealing with this particular transition correctly (I'm sorry I don't know enough about Gatsby to comment on specifics)

**Comment by greglobinski** [comment]
@mansona 
If you want a behavior as you described open  [src/utils/shared.js](https://github.com/greglobinski/gatsby-starter-personal-blog/blob/c679c38c97679c621412f801400daa3dbf439108/src/utils/shared.js#L17-L23) and uncomment the code in `featureNavigator`

```
          // uncomment following lines if you want to count featuring Navigator as a visit
          // to index page ('/'), you have to also uncomment import { navigateTo }...
          /*
          setTimeout(() => {
            navigateTo("/");
          }, 1000);
          */
```
