### ISSUE TITLE
Ability to add runkit snippets in markdown

### ISSUE THREAD

**Issue by siwalikm** [greglobinski/gatsby-starter-personal-blog#76]
Adding ability to have runkit snippets in markdown posts.

**Comment by justsml** [comment]
Great idea!

Maybe this should be a separate gatsby plugin? 

Btw, I happen to have written a script to auto-embed Runkit (based on highlight.js) code blocks. 😸 

Let me know if we're talking about a similar thing: https://fpromises.io 

Either way I might be able to work on a react-ified plugin...
What features/options might it need?

- CSS Overides? (scroll to results, or bg color for results)
- Editor Theming? (i think they added support)
- Include/exclude filter lists? (i used a simple method in my script)
- Embedding links? (i needed to have all my code version controlled - NOT duplicated on a remote service w/ links to coordinate)

**Comment by siwalikm** [comment]
@justsml A react plugin for embedding runkit sounds great! dev.to website already does something similar, maybe I'll check their source code to find something. If you start working on one though, add me as a contributor to your project, would love to help out with some issues.
