### ISSUE TITLE
reload problem in production env.

### ISSUE THREAD

**Issue by emrahsonm3z** [greglobinski/gatsby-starter-personal-blog#91]
hi,
I'm working on the https://github.com/greglobinski/gatsby-starter-personal-blog project for v2. I have published the project to netlify. There's something wrong with that. There is no problem when the page is first loaded. However, after entering a post, such as "component - src-pages-index.js" source file is not loaded when refreshed..

link : https://admiring-agnesi-af7a2e.netlify.com/

First load: 
![1](https://user-images.githubusercontent.com/9351440/54062335-6f910700-4216-11e9-887b-b6988cf93044.png)

After loads:
![2](https://user-images.githubusercontent.com/9351440/54062336-70299d80-4216-11e9-8838-db1e66d49fcf.png)

![3](https://user-images.githubusercontent.com/9351440/54062489-5dfc2f00-4217-11e9-8d59-c43bf67a35f9.png)

**Comment by greglobinski** [comment]
Yup, it's a known problem #64 but I'm not longer try to solve it, I decided to rewrite the codebase from scratch using different stack #89 

So, sorry but I can't help.
