### ISSUE TITLE
gatsby new error

### ISSUE THREAD

**Issue by rccclr** [greglobinski/gatsby-starter-personal-blog#96]
Please help for this error in gatsby new.

Many thanks

![image](https://user-images.githubusercontent.com/5550864/60755403-8d694f80-9fef-11e9-92a2-bb19eb859fca.png)

**Comment by jamezrin** [comment]
Try updating sharp 0.22.1 or downgrade your node from 12 (which you are using) to something like 10

**Comment by rccclr** [comment]
Many thanks for your response.

With node 10.16 work fine!!

Thanks
